--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.5

-- Started on 2022-10-31 21:58:53

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--



--
-- TOC entry 3369 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 213 (class 1259 OID 29587)
-- Name: purchases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.purchases (
    id bigint NOT NULL,
    storehouse_id bigint
);


--
-- TOC entry 214 (class 1259 OID 29592)
-- Name: document_purchase_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.purchases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_purchase_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 29574)
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    vendor_code character varying(256) NOT NULL,
    name character varying(256) NOT NULL,
    last_purchase_price numeric,
    last_sale_price numeric,
    id bigint NOT NULL
);


--
-- TOC entry 221 (class 1259 OID 29637)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 29593)
-- Name: purchase_products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.purchase_products (
    purchase_id bigint NOT NULL,
    vendor_code character varying NOT NULL,
    quantity bigint NOT NULL,
    price numeric NOT NULL
);


--
-- TOC entry 218 (class 1259 OID 29612)
-- Name: sale_products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sale_products (
    sale_id bigint NOT NULL,
    vendor_code character varying(256) NOT NULL,
    quantity bigint NOT NULL,
    price numeric NOT NULL
);


--
-- TOC entry 216 (class 1259 OID 29604)
-- Name: sales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales (
    id bigint NOT NULL,
    storehouse_id bigint NOT NULL
);


--
-- TOC entry 217 (class 1259 OID 29611)
-- Name: sales_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 29581)
-- Name: storehouse_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.storehouse_product (
    storehouse_id bigint NOT NULL,
    product_quantity bigint NOT NULL,
    product_id bigint NOT NULL
);


--
-- TOC entry 209 (class 1259 OID 29569)
-- Name: storehouses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.storehouses (
    id bigint NOT NULL,
    name character varying(256) NOT NULL
);


--
-- TOC entry 212 (class 1259 OID 29586)
-- Name: storehouses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.storehouses ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.storehouses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 29629)
-- Name: transfer_products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transfer_products (
    transfer_id bigint NOT NULL,
    vendor_code character varying(256) NOT NULL,
    quantity bigint NOT NULL
);


--
-- TOC entry 219 (class 1259 OID 29622)
-- Name: transfers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transfers (
    id bigint NOT NULL,
    storehouse_from_id bigint NOT NULL,
    storehouse_to_id bigint NOT NULL
);


--
-- TOC entry 222 (class 1259 OID 29684)
-- Name: transfers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transfers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transfers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3211 (class 2606 OID 29591)
-- Name: purchases document_purchase_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT document_purchase_pkey PRIMARY KEY (id);


--
-- TOC entry 3205 (class 2606 OID 29645)
-- Name: products products_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pk PRIMARY KEY (id);


--
-- TOC entry 3216 (class 2606 OID 29610)
-- Name: sales sales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT sales_pkey PRIMARY KEY (id);


--
-- TOC entry 3209 (class 2606 OID 29683)
-- Name: storehouse_product storehouse_product_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.storehouse_product
    ADD CONSTRAINT storehouse_product_pk PRIMARY KEY (storehouse_id, product_id);


--
-- TOC entry 3202 (class 2606 OID 29573)
-- Name: storehouses storehouses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.storehouses
    ADD CONSTRAINT storehouses_pkey PRIMARY KEY (id);


--
-- TOC entry 3220 (class 2606 OID 29628)
-- Name: transfers transfers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transfers
    ADD CONSTRAINT transfers_pkey PRIMARY KEY (id);


--
-- TOC entry 3213 (class 1259 OID 29603)
-- Name: fki_products_document_purchase_fk; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fki_products_document_purchase_fk ON public.purchase_products USING btree (purchase_id);


--
-- TOC entry 3203 (class 1259 OID 29691)
-- Name: id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX id_index ON public.products USING btree (id);


--
-- TOC entry 3200 (class 1259 OID 29693)
-- Name: id_storehouse_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX id_storehouse_index ON public.storehouses USING btree (id);


--
-- TOC entry 3212 (class 1259 OID 29695)
-- Name: purchases_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX purchases_id_index ON public.purchases USING btree (id);


--
-- TOC entry 3217 (class 1259 OID 29698)
-- Name: sale_products_f_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sale_products_f_index ON public.sale_products USING btree (sale_id);


--
-- TOC entry 3214 (class 1259 OID 29697)
-- Name: sales_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_id_index ON public.sales USING btree (id);


--
-- TOC entry 3207 (class 1259 OID 29694)
-- Name: storehouse_product_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX storehouse_product_index ON public.storehouse_product USING btree (product_id, storehouse_id);


--
-- TOC entry 3221 (class 1259 OID 29700)
-- Name: transfer_products_f_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transfer_products_f_index ON public.transfer_products USING btree (transfer_id);


--
-- TOC entry 3218 (class 1259 OID 29699)
-- Name: transfers_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transfers_id_index ON public.transfers USING btree (id);


--
-- TOC entry 3206 (class 1259 OID 29692)
-- Name: vendor_code_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vendor_code_index ON public.products USING btree (vendor_code);


--
-- TOC entry 3222 (class 2606 OID 29598)
-- Name: purchase_products products_document_purchase_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_products
    ADD CONSTRAINT products_document_purchase_fk FOREIGN KEY (purchase_id) REFERENCES public.purchases(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 3223 (class 2606 OID 29617)
-- Name: sale_products sale_products_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_products
    ADD CONSTRAINT sale_products_fk FOREIGN KEY (sale_id) REFERENCES public.sales(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3224 (class 2606 OID 29632)
-- Name: transfer_products transfer_products_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transfer_products
    ADD CONSTRAINT transfer_products_fk FOREIGN KEY (transfer_id) REFERENCES public.transfers(id) ON UPDATE CASCADE ON DELETE CASCADE;


-- Completed on 2022-10-31 21:58:54

--
-- PostgreSQL database dump complete
--

